apiVersion: v1
kind: Secret
metadata:
  name: demo-api-secret
  namespace: demo
  labels:
    app: demo-api
type: Opaque
stringData:
  appsettings.Production.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "ConnectionStrings": {
        "DefaultConnection": "Host=postgresql.postgresql.svc.cluster.local;Port=5432;Username=nexus;Password=fmXGrhB8Z3y2QE7PsqdYjg6x4;Database=demo"
      }
    }