apiVersion: v1
kind: Service
metadata:
  name: demo-webapi-service
  namespace: demo
  labels:
    app: demo-webapi 
spec:
  selector:
    app: demo-webapi-deployment
  ports:
  - port: 443
    targetPort: 443
