version: "3.9"
services:
  webapi:
    image: province-api
    build:
      context: .
      dockerfile: ./Demo.API/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  db:
    image: postgres:15.1
    container_name: nexus-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd!
      - POSTGRES_USER=nexus
      #- POSTGRES_MULTIPLE_DATABASES=nexus,sonarqubedb
    volumes:
      - ./postgres/extensions/init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
      - ./postgres/data:/var/lib/postgresql/data      
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure